# Generated by Django 3.2.8 on 2021-11-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.CharField(default='', max_length=100)),
                ('contest_title', models.CharField(default='', max_length=500)),
                ('contest_format', models.CharField(choices=[('AtCoder', 'AtCoder'), ('ACM', 'ACM'), ('OI', 'OI')], default='OI', max_length=100)),
                ('contest_rating_range', models.CharField(default='0-5000', max_length=50)),
                ('contest_rated', models.BooleanField(default=True)),
            ],
        ),
    ]
