# Generated by Django 3.2.8 on 2021-11-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contestant_count',
            field=models.IntegerField(default=0),
        ),
    ]
