# Generated by Django 3.2.8 on 2021-11-28 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_contest_contestant_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contest_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='contest',
            name='contest_schedule',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
