# Generated by Django 3.2.8 on 2021-11-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20211128_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contest_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
