# Generated by Django 3.2.8 on 2021-11-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_alter_contest_contest_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contest_long',
            field=models.CharField(default='01:00:00', max_length=20),
        ),
    ]
