# Generated by Django 3.2.8 on 2021-11-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_contest_contest_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contest_status',
            field=models.CharField(choices=[('SCHEDULE', 'Schedule'), ('RUNNING', 'Running'), ('ARCHIVED', 'Archived')], default='SCHEDULE', max_length=50),
        ),
    ]
