# Generated by Django 3.2.8 on 2021-11-28 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_profile_id'),
        ('contest', '0007_contest_contest_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='id',
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_id',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(default=1)),
                ('scoring', models.CharField(blank=True, default='', max_length=300)),
                ('total_score', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('total_time', models.CharField(default='00:00:00', max_length=50)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profile')),
            ],
        ),
    ]
