# Generated by Django 3.2.8 on 2021-11-29 02:23

from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_profile_id'),
        ('contest', '0009_alter_leaderboard_scoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_problem_id', models.CharField(default='A', max_length=1)),
                ('problem_id', models.CharField(default='', max_length=50)),
                ('problem_title', models.CharField(default='', max_length=100)),
                ('problem_description', martor.models.MartorField(default='')),
                ('problem_sample_in', models.TextField(default='')),
                ('problem_sample_out', models.TextField(default='')),
                ('problem_hidden_in', models.TextField(default='')),
                ('problem_hidden_out', models.TextField(default='')),
                ('problem_time_limit', models.DecimalField(decimal_places=3, default=1.0, max_digits=5)),
                ('problem_memory_limit', models.IntegerField(default=65536)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profile')),
            ],
        ),
    ]
