# Generated by Django 3.2.8 on 2021-11-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_auto_20211129_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_score',
            field=models.DecimalField(decimal_places=3, default=100.0, max_digits=6),
        ),
    ]
