# Generated by Django 3.2.8 on 2021-11-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_problem_problem_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_accepted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_wrongans',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_score',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
        ),
    ]
