# Generated by Django 3.2.8 on 2021-11-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211127_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='win',
            field=models.IntegerField(default=0),
        ),
    ]
