# Generated by Django 3.2.8 on 2021-12-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
