# Generated by Django 3.2.8 on 2021-12-16 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_announcement_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
